### ISSUE TITLE
SMCRadeonGPU doesn't seem to work

### ISSUE THREAD

**Issue by hipco** [ChefKissInc/RadeonSensor#3]
Still no readings from Navi 5700 (0x731F) GPU DIe 1 and GPU Die 2.

With 0.3.3 GPU Die 1 reading is ok, GPU Die 2 is empty.

![Screenshot](https://github.com/NootInc/RadeonSensor/assets/59048928/cfd4f40e-8a8f-4f32-ba92-e8f08d13cf84)

Ventura 13.4
Radeon 5700

**Comment by ChefKissInc** [comment]
Does the RadeonSensor gadget itself show readings?

**Comment by hipco** [comment]
Yes the gadget shows the correct reading. Seems to be related to iStats.
![Screenshot](https://github.com/NootInc/RadeonSensor/assets/59048928/be627d3d-9ae1-4b52-82c5-a4e479ba9b10)

**Comment by ChefKissInc** [comment]
Have you updated SMCRadeonSensor?

**Comment by hipco** [comment]
Yes. SMCRadeonGPU.kext 1.1.0 and RadeonSensor.kext 1.1.0

**Comment by Xenobreaker** [comment]
Hello, I would also like to pitch in that I'm also experiencing the same as above while using an AMD Radeon Pro W5700. 
I'm also on version 1.1.0 of the kexts. I don't think it matters but I'm using Monterey.

**Comment by ChefKissInc** [comment]
I'm unable to stop the issue code-wise, are you sure all your kexts are up-to-date? (VirtualSMC, etc)

**Comment by ChefKissInc** [comment]
Just tested iStat Menus on my AMD laptop, and I get no GPU temperature sensor SMC keys either. SMCRadeonGPU is loaded according to kextstat. I wonder what's going wrong.

**Comment by hipco** [comment]
Maybe it's related to issue 14 from aluveitie

SMC Key for TGDD and TCGC - Stats temperature not showing #14
[https://github.com/aluveitie/RadeonSensor/issues/14](url)

**Comment by ChefKissInc** [comment]
Can you try this?
[SMCRadeonGPU-1.1.0-DEBUG.zip](https://github.com/NootInc/RadeonSensor/files/12206618/SMCRadeonGPU-1.1.0-DEBUG.zip)

**Comment by hipco** [comment]
Sorry doesn't work. Is this enough for logging?

                <key>Debug</key>
                <dict>
                        <key>DisableWatchDog</key>
                        <true/>
                        <key>DisplayDelay</key>
                        <integer>0</integer>
                        <key>DisplayLevel</key>
                        <integer>2147483714</integer>
                        <key>Target</key>
                        <integer>67</integer>
                </dict>

**Comment by ChefKissInc** [comment]
Don't need logs

**Comment by ChefKissInc** [comment]
[SMCRadeonGPU-1.1.0-DEBUG.zip](https://github.com/NootInc/RadeonSensor/files/12206701/SMCRadeonGPU-1.1.0-DEBUG.zip)
What about this? @hipco

**Comment by hipco** [comment]
No success. Is the reading working now with your AMD laptop?

**Comment by iRet** [comment]
Same issue on my side. No more readings from iStat Menus after kext update.

**Comment by ChefKissInc** [comment]
@iRet I will fix it, just give me some time

**Comment by Datisit** [comment]
I've just freshly installed the latest kexts for my new Radeon VII in my iMac19,1 Hack.
MacOS 12.6.8

Same issue I believe, no readings.

**Comment by Datisit** [comment]
Hey no worries at all!

Is there anything us users can do to help test in some way?

All good if not, all your dev efforts are much appreciated.

**Comment by VisualEhrmanntraut** [comment]
Hi. Just earlier today I got my test machine back to working order. I will begin debugging tomorrow.

**Comment by VisualEhrmanntraut** [comment]
@Datisit, @iRet and @hipco can you try the below and tell me if it works for you?
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574084/RadeonSensor-1.2.0-DEBUG.zip)
[SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574086/SMCRadeonGPU-1.2.0-DEBUG.zip)

<img width="367" alt="Screen Shot 2023-09-11 at 11 55 00" src="https://github.com/ChefKissInc/RadeonSensor/assets/30368284/b906ea43-daea-47d6-a320-d887d0d8065a">

Stat works for me at the very least.

**Comment by hipco** [comment]
Sorry,  but my Radeon 5700 sensor doesn't show up under iStats 6.71 with SMBIOS MacPro7,1.
 
![istats](https://github.com/ChefKissInc/RadeonSensor/assets/59048928/cd8f99d6-21e9-4a22-9cc2-029006756549)

**Comment by VisualEhrmanntraut** [comment]
I think iStats is bugged. Because it works in Stats and I can see the SMC keys when I use the "smc" tool included with VirtualSMC

**Comment by VisualEhrmanntraut** [comment]
@hipco Can you also test with the following?
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574610/RadeonSensor-1.2.0-DEBUG.zip)
[SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574611/SMCRadeonGPU-1.2.0-DEBUG.zip)

**Comment by hipco** [comment]
No luck either. The funny thing is under CPU the correct readings from my 5700 are present (Core Clock 9MHz ??). Maybe iStats is bugged but with aluveites 0.3.3 version the temp sensor is additionally showing up under SENSORS.

![istats](https://github.com/ChefKissInc/RadeonSensor/assets/59048928/0be8af9f-1eca-48d4-9556-a90e640584d0)

**Comment by Datisit** [comment]
Very little change for my Radeon VII, showing a 0º value now rather than –º like it used to in the Sensors in iStat, but also not showing anything useful in Stats apart from Utilisation, which was always working in iStat.
![Screenshot 2023-09-12 at 12 06 55](https://github.com/ChefKissInc/RadeonSensor/assets/14685/37f9c22a-7ad6-4cf6-962c-ec8781ae4657)
![Screenshot 2023-09-12 at 12 06 59](https://github.com/ChefKissInc/RadeonSensor/assets/14685/5b4f59d9-04c1-491d-a479-445811105d15)
![Screenshot 2023-09-12 at 12 10 32](https://github.com/ChefKissInc/RadeonSensor/assets/14685/19ed0386-532b-4c47-9ef6-e923677ea172)
![Screenshot 2023-09-12 at 12 12 37](https://github.com/ChefKissInc/RadeonSensor/assets/14685/48e6d498-8ee4-4a7c-a964-94eefcfe3551)

**Comment by VisualEhrmanntraut** [comment]
@Datisit With which of the two builds

**Comment by Datisit** [comment]
@VisualEhrmanntraut The one you linked to me (1.2.0):

> @Datisit, @iRet and @hipco can you try the below and tell me if it works for you? [RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574084/RadeonSensor-1.2.0-DEBUG.zip) [SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12574086/SMCRadeonGPU-1.2.0-DEBUG.zip)
> 
> <img alt="Screen Shot 2023-09-11 at 11 55 00" width="367" src="https://user-images.githubusercontent.com/30368284/266964721-b906ea43-daea-47d6-a320-d887d0d8065a.png">
> "Stats" works for me at the very least.

**Comment by VisualEhrmanntraut** [comment]
@Datisit Was the kext order correct? Someone in our Telegram supergroup that tested it had it ordered incorrectly, and it exhibited the same behaviour.

**Comment by Datisit** [comment]
Just Lilu before all the others, right?
For Example:
![Screenshot 2023-09-12 at 16 06 43](https://github.com/ChefKissInc/RadeonSensor/assets/14685/4c71b6e8-39c0-4f20-a337-a73834ae582e)

**Comment by VisualEhrmanntraut** [comment]
The order of dependency is as follows: Lilu > RadeonSensor > VirtualSMC > SMCRadeonGPU

**Comment by Datisit** [comment]
Like so? (ignoring other kexts):
![Screenshot 2023-09-12 at 16 09 49](https://github.com/ChefKissInc/RadeonSensor/assets/14685/ad8f5cb9-8642-4723-b4e2-aa4766aa95fb)

**Comment by VisualEhrmanntraut** [comment]
Yes.

**Comment by Datisit** [comment]
Yep, that's how I have it for my current booted session.

**Comment by VisualEhrmanntraut** [comment]
@Datisit And you’ve got both RadeonSensor *and* SMCRadeonGPU from that build?

**Comment by Datisit** [comment]
Yes, both of them it looks like:
![Screenshot 2023-09-12 at 16 13 31](https://github.com/ChefKissInc/RadeonSensor/assets/14685/fffd226c-93fb-4c1d-94cd-e6c835278310)

**Comment by VisualEhrmanntraut** [comment]
Oh, the RadeonSensor gadget is showing 0°C? That's a different issue, did it work with the upstream?

**Comment by Datisit** [comment]
Every app is show 0ºC, but also not showing the speeds or any other info, just the processor utilisation and memory.
Sorry, what's the upstream?

**Comment by VisualEhrmanntraut** [comment]
Aluveitie’s

**Comment by Datisit** [comment]
The old dev on this project?
I'm really sorry, I'm not following what you're asking?

**Comment by VisualEhrmanntraut** [comment]
@Datisit My question is if your Radeon VII worked with the kext from the old dev.

**Comment by Datisit** [comment]
Ok, just tested with 0.3.3.
The only difference appears to be within iStat Sensors, there's a GPU temp ready now but it's just static at 34ºC:
![Screenshot 2023-09-12 at 16 52 58](https://github.com/ChefKissInc/RadeonSensor/assets/14685/f769ade2-cb5c-4923-bde4-64991866fe8a)

**Comment by hipco** [comment]
These 4 keys are missing with your implementation compared to aluveites. Dumped with smcread -s (0.3.3 against latest debug 1.2.0)

[TG0D] type [sp78] 73703738 len [ 2] attr [80] -> 2D00
[TG0P] type [sp78] 73703738 len [ 2] attr [80] -> 2D00
[TG0d] type [sp78] 73703738 len [ 2] attr [80] -> 2D00
[TG0p] type [sp78] 73703738 len [ 2] attr [80] -> 2D00

**Comment by VisualEhrmanntraut** [comment]
@hipco I see them on my machine using my build

**Comment by hipco** [comment]
This part of the code seems to be ignored on my 5700. Maybe the getCardCount() function.

auto gpuCount = this->rsensor->getCardCount();
    for (auto i = 0; i < gpuCount; i++) {
        VirtualSMCAPI::addKey(KeyTGxD(i), vsmcPlugin.data,
            VirtualSMCAPI::valueWithSp(0, SmcKeyTypeSp78, new RGPUTempValue(this->rsensor, i)));
        VirtualSMCAPI::addKey(KeyTGxP(i), vsmcPlugin.data,
            VirtualSMCAPI::valueWithSp(0, SmcKeyTypeSp78, new RGPUTempValue(this->rsensor, i)));
        VirtualSMCAPI::addKey(KeyTGxd(i), vsmcPlugin.data,
            VirtualSMCAPI::valueWithSp(0, SmcKeyTypeSp78, new RGPUTempValue(this->rsensor, i)));
        VirtualSMCAPI::addKey(KeyTGxp(i), vsmcPlugin.data,
            VirtualSMCAPI::valueWithSp(0, SmcKeyTypeSp78, new RGPUTempValue(this->rsensor, i)));
    }

**Comment by VisualEhrmanntraut** [comment]
Add `-rsensordbg msgbuf=1048576` to your boot args, and after you boot back to macOS run `sudo dmesg | grep -i RadeonSensor` and show the output here

**Comment by hipco** [comment]
I need working debug settings in config.plist. Mine doesn't work, no output from dmesg.

            <key>Debug</key>
            <dict>
                    <key>DisableWatchDog</key>
                    <true/>
                    <key>DisplayDelay</key>
                    <integer>0</integer>
                    <key>DisplayLevel</key>
                    <integer>2147483714</integer>
                    <key>Target</key>
                    <integer>67</integer>
            </dict>

**Comment by VisualEhrmanntraut** [comment]
Those are OC’s settings, try adding the DebugEnhancer kext

**Comment by hipco** [comment]
GPU Count 0. As imagined


[    0.376189]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    0.386830]: SMCRadeonGPU      init: @ (DBG) Card count: 0
[    2.759322]: SMCRadeonGPU   smcrgpu: @ (DBG) Submitted plugin
[    7.258445]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".
[    7.583448]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".
[    7.745841]: [3:0:0] [AGDC] AMDRadeonX6000_AmdAgdcServices::vendor_doDeviceAttribute() ??? Controller is NOT enabled so SKIP. cmd:[       3].
[    7.751484]: [3:0:0] [FB:0] AmdRadeonFramebuffer::setCursorImage() !!! Driver is offline.
[    7.751487]: [3:0:0] [FB:1] AmdRadeonFramebuffer::setCursorImage() !!! Driver is offline.
[    7.751489]: [3:0:0] [FB:2] AmdRadeonFramebuffer::setCursorImage() !!! Driver is offline.
[    7.751491]: [3:0:0] [FB:3] AmdRadeonFramebuffer::setCursorImage() !!! Driver is offline.
[    7.751539]: PMRD: ATY,RadeonFramebuffer tag flags 200
[    7.751560]: PMRD: ATY,RadeonFramebuffer tag flags 200
[    7.751572]: PMRD: ATY,RadeonFramebuffer tag flags 200
[    7.751583]: PMRD: ATY,RadeonFramebuffer tag flags 200

**Comment by VisualEhrmanntraut** [comment]
@hipco Can you try this?
[RadeonGadget-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12586256/RadeonGadget-1.2.0-DEBUG.zip)
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12586253/RadeonSensor-1.2.0-DEBUG.zip)
[SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12586254/SMCRadeonGPU-1.2.0-DEBUG.zip)

**Comment by VisualEhrmanntraut** [comment]
Are you using the kexts after the edit

**Comment by hipco** [comment]
Before and after it doesn't make any difference. It was just a thought that Whatevergreen should be loaded before Radeonsensor but it doesn't matter.

**Comment by VisualEhrmanntraut** [comment]
Need the logs from the later revision. Unless I uploaded the wrong files. Hopefully not

**Comment by hipco** [comment]
Present config:

Kext order Lilu->Radeonsensor->VirtualSMC->SMCRadeon->Whatevergreen

RadeonSensor.kext 1.2.0 20230912 14:17
SMCRadeonGPU.kext 1.2.0 20230912 14:17

sudo dmesg |grep -i Radeon                                            
[    0.377443]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    0.377446]: RadeonSensor   rsensor: @ getMatchingServices returned null
[    0.377577]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    0.377580]: RadeonSensor   rsensor: @ getMatchingServices returned null
[    2.675648]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    2.675654]: RadeonSensor   rsensor: @ getMatchingServices returned null
[    2.676297]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    2.676301]: RadeonSensor   rsensor: @ getMatchingServices returned null
[    2.752534]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    2.753305]: SMCRadeonGPU      init: @ (DBG) Card count: 0
[    2.758289]: SMCRadeonGPU   smcrgpu: @ (DBG) Submitted plugin
[    7.532319]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".
[    7.891546]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".

**Comment by VisualEhrmanntraut** [comment]
@hipco Guess I sent the wrong build somehow. Here they are again. Pretty sure they are correct.
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12598396/RadeonSensor-1.2.0-DEBUG.zip)
[SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12598397/SMCRadeonGPU-1.2.0-DEBUG.zip)

**Comment by hipco** [comment]
What should I say? A kiss for the chef, at least. Well done and thanks !!!!

![cpu](https://github.com/ChefKissInc/RadeonSensor/assets/59048928/5b382cbb-ecb1-4325-ba5f-77b36e7dd46f)
![sensors](https://github.com/ChefKissInc/RadeonSensor/assets/59048928/c1bffa92-a815-4c9b-a613-2f6def0bc48e)

 sudo dmesg |grep -i radeon                                           
Password:
[    0.353822]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.364544]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    2.662806]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    2.663428]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    2.740389]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740394]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740397]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740400]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740403]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740405]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740408]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740411]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740414]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740416]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740419]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740422]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740424]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740427]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740429]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740432]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    2.740435]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 60400 value
[    2.740437]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    2.740440]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    2.740443]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 60400 value
[    2.740445]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    2.740448]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 30000 value
[    2.740454]: RadeonSensor   rsensor: @ (DBG) Family: Navi
[    2.740457]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    2.740460]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 40300 value
[    2.740463]: RadeonSensor   rsensor: @ (DBG) Found 1 cards
[    2.740978]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    2.741770]: SMCRadeonGPU      init: @ (DBG) Card count: 1
[    2.742150]: SMCRadeonGPU   smcrgpu: @ (DBG) Submitted plugin
[    7.532292]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".
[    7.906809]: [3:0:0][GPUCAP] refresh() --- Branding - family: "Radeon RX"; device: "5700"; model: "AMD Radeon RX 5700".

**Comment by VisualEhrmanntraut** [comment]
You're welcome.

**Comment by Datisit** [comment]
> @hipco Guess I sent the wrong build somehow. Here they are again. Pretty sure the following are up-to-date with my local changes.
> 
> [RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12598396/RadeonSensor-1.2.0-DEBUG.zip) [SMCRadeonGPU-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12598397/SMCRadeonGPU-1.2.0-DEBUG.zip)
> 
> EDIT: To be of utmost precision, you must swap BOTH of the kexts with the builds I'm posting. You cannot just swap SMCRadeonGPU and call it a day.

Hey I just tested these and the RELEASE versions and I'm still not getting the Radeon VII info.
Just the 0ºC for temp.

I've also added DebugEnhancer, and added the -rsensordbg msgbuf=1048576 boot arg, but I'm not getting any 'Radeon' hit in the dmesg output. I get a lot, but nothing from RadeonSensor

**Comment by Datisit** [comment]
Yep have currently got the DEBUG ones loaded in.

**Comment by VisualEhrmanntraut** [comment]
Then RadeonSensor failed to inject.

**Comment by Datisit** [comment]
They're both listed when I run kextstat

**Comment by Datisit** [comment]
Ok, so both DEBUG kexts in the Kexts folder.
My load order is: Lilu->Radeonsensor->VirtualSMC->Whatevergreen->SMCRadeon
My boot args is : -v keepsyms=1 -rsensordbg msgbuf=1048576
And I'm running sudo dmesg |grep -i Radeon

**Comment by VisualEhrmanntraut** [comment]
@Datisit Save the entire dmesg to a file and send it here
i.e `sudo dmesg > ~/Desktop/dmesg.txt`

**Comment by Datisit** [comment]
[dmesg.txt](https://github.com/ChefKissInc/RadeonSensor/files/12614452/dmesg.txt)

Thanks so much for taking the time to help me, I really appreciate it.

**Comment by VisualEhrmanntraut** [comment]
@Datisit Neither the boot arg nor DebugEnhancer are active; the dmesg is trimmed to ~128KiB.

**Comment by Datisit** [comment]
Ah of course, so sorry!
Yeah I didn’t add the DebugEnhance to my config. 

I’ll get it going properly in an hour when I’m back home.

**Comment by Datisit** [comment]
Ok... Here we are!:

`[    0.767142]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.769649]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.782861]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.787551]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.949788]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.378873]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.386863]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.394576]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.402178]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.409668]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.417093]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.424436]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.431716]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.438994]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.446182]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.453081]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.459687]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.466168]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.472539]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 8086 value
[    1.478620]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    1.484704]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 60400 value
[    1.490860]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1CC1 value
[    1.496759]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1CC1 value
[    1.502657]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    1.508230]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 60400 value
[    1.513589]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    1.518653]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 30000 value
[    1.523508]: RadeonSensor   rsensor: @ (DBG) Family: Arctic Islands
[    1.528012]: RadeonSensor     iokit: @ (DBG) getOSData vendor-id has 1002 value
[    1.532800]: RadeonSensor     iokit: @ (DBG) getOSData class-code has 40300 value
[    1.537658]: RadeonSensor   rsensor: @ (DBG) Found 1 cards
[    1.542201]: RadeonSensor   rsensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    1.547951]: SMCRadeonGPU      init: @ (DBG) Card count: 1
[    1.548007]: SMCRadeonGPU   smcrgpu: @ (DBG) Submitted plugin
[   18.967960]: RadeonSensor   rsensor: @ (DBG) Using BAR, located at 0x5`

**Comment by VisualEhrmanntraut** [comment]
@Datisit try this
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12614903/RadeonSensor-1.2.0-DEBUG.zip)

**Comment by Datisit** [comment]
[    0.769715]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.771405]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.783920]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[    0.786998]: RadeonSensor   rsensor: @ Failed to get iterator over IOPCIDevice
[   22.764778]: Sandbox: nsattributedstri(723) deny(1) iokit-open-user-client AMDRadeonX5000_AMDAccelDeviceSandbox: donotdisturbd(616) deny(1) mach-lookup com.apple.icloud.fmfdSandbox: nsattributedstri(723) deny(1) mach-lookup com.apple.cvmsServSandbox: nsattributedstri(723) deny(1) mach-lookup com.apple.PowerManagement.controlAMFI: constraint violation /Applications/Timemator.app/Contents/Frameworks/DateHelper.framework/Versions/A/DateHelper has entitlements but is not a main binary

**Comment by VisualEhrmanntraut** [comment]
So I assume it doesn't work?

**Comment by Datisit** [comment]
Yeah, nothing had changed, except back to just a '-' value next to the Proximity temp

**Comment by VisualEhrmanntraut** [comment]
Try this @Datisit 
[RadeonSensor-1.2.0-DEBUG.zip](https://github.com/ChefKissInc/RadeonSensor/files/12615036/RadeonSensor-1.2.0-DEBUG.zip)

**Comment by VisualEhrmanntraut** [comment]
@Datisit *crickets*

**Comment by Datisit** [comment]
Sorry, had to work on my machine - will retest tomorrow!

**Comment by Datisit** [comment]
Ok results of 1.3.0 debug versions:

It looks like i have temperature readings now.
Showing up in iStat Sensors, and Stats and RadeonSensor app.
![Screenshot 2023-09-16 at 13 55 23](https://github.com/ChefKissInc/RadeonSensor/assets/14685/5ed06845-77ba-4b74-958a-2f30411e4565)


But nothing in the iStat CPU/GPU area.
Here's stats screenshot for simplicity:

![Screenshot 2023-09-16 at 13 56 03](https://github.com/ChefKissInc/RadeonSensor/assets/14685/4b0b28d4-f093-4cca-867d-0b64ce5d1273)

Here's the dmesg output:

[    0.784589]: RadeonSensor   RSensor: @ Failed to get iterator over IOPCIDevice
[    0.787184]: RadeonSensor   RSensor: @ Failed to get iterator over IOPCIDevice
[    0.799848]: RadeonSensor   RSensor: @ Failed to get iterator over IOPCIDevice
[    0.801189]: RadeonSensor   RSensor: @ Failed to get iterator over IOPCIDevice
[    0.984171]: RadeonSensor    RSCard: @ (DBG) Arctic Islands
[    0.984178]: RadeonSensor    RSCard: @ (DBG) Using BAR5, located at 0xffffffd5f392a000
[    0.984183]: RadeonSensor   RSensor: @ (DBG) Found 1 cards
[    0.984296]: RadeonSensor   RSensor: @ Copyright 2023 ChefKiss Inc. If you've paid for this, you've been scammed.
[    0.984551]: SMCRadeonGPU      init: @ (DBG) Card count: 1
[    0.984609]: SMCRadeonGPU   smcrgpu: @ (DBG) Submitted plugin
[   22.914277]: Sandbox: nsattributedstri(725) deny(1) iokit-open-user-client AMDRadeonX5000_AMDAccelDeviceAMFI: code signature validation failed.

**Comment by VisualEhrmanntraut** [comment]
Well, that’s not an issue with the kext.

**Comment by Datisit** [comment]
Sorry, of course — I forgot it's only for temperature.

Is there anything that can get me the other data for the Radeon VII?

**Comment by Datisit** [comment]
And hey, thanks so much for working on this, really helpful to be able to monitor temps again now.

**Comment by VisualEhrmanntraut** [comment]
@Datisit Not as far as I know. But I’ll certainly add more readings at some point. You’re welcome.
