### ISSUE TITLE
macOS Sonoma kernel panics when using RadeonSensor.kext, not SMCRadeonGPU.kext though. 

### ISSUE THREAD

**Issue by Trijal08** [ChefKissInc/RadeonSensor#7]
**Describe the bug**
The title says it all.

**To Reproduce**
1. Use RadeonSensor.kext. 
2. Be dissapointed and frustrated because it kernel panics!!!

**Expected behavior**
Just wanted to use the RadeonGadget to see GPU temps. 

**Screenshots**

**System Information:**
 - macOS Version: [macOS Sonoma 14]
 - CPU: [AMD Ryzen 7 3700U]

**Comment by VisualEhrmanntraut** [comment]
@Trijal08 SMCRadeonGPU depends on RadeonSensor; it must be after it

**Comment by VisualEhrmanntraut** [comment]
Ok
