### ISSUE TITLE
Boot failed and restart soon for ventura 13.6.1

### ISSUE THREAD

**Issue by moqsien** [ChefKissInc/RadeonSensor#8]
**Describe the bug**
Boot failure occurs very soon after pressing <Install MacOS>. And no debug info can be captured as opencore restart immediately.

**To Reproduce**

Using kexts from current fork will cause the problem described above.However, kexts from [aluveitie v0.3.3](https://github.com/aluveitie/RadeonSensor) works fine.

**System Information:**
 - macOS Version: [e.g. macOS 13.6.1]
 - CPU: [e.g. AMD Ryzen 5 3550(Vega 8)]
 - Graphics: RX560X

**Comment by VisualEhrmanntraut** [comment]
@moqsien SMCRadeonGPU must be after RadeonSensor in kexts list

**Comment by moqsien** [comment]
> @moqsien SMCRadeonGPU must be after RadeonSensor in kexts list

Thanks. It works.
